# Generated by Django 3.2 on 2023-08-06 19:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230807_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientToShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимальное количество = 1')], verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Ингредиент для списка покупок',
            },
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_shoppinglist',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='recipe',
        ),
        migrations.AddField(
            model_name='ingredienttoshoppinglist',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='ingredienttoshoppinglist',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.shoppinglist', verbose_name='Список покупок'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.IngredientToShoppingList', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
