# Generated by Django 4.2.4 on 2023-08-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipeinshoppinglist_remove_shoppinglist_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeinshoppinglist',
            options={'verbose_name': 'Рецепт в корзине', 'verbose_name_plural': 'Рецепты в корзине'},
        ),
    ]
